name: Deploy to Staging

on:
     push:
          branches:
               - staging

jobs:
     deploy:
          runs-on: self-hosted

          steps:
               - name: Checkout kode
                 uses: actions/checkout@v4

               - name: Restore NuGet
                 shell: powershell
                 run: |
                      C:\nuget.exe restore "SKK\SKK.sln"

               - name: Build Release
                 shell: powershell
                 run: |
                      & "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" "SKK\SKK.sln" /p:Configuration=Release /p:Platform="Any CPU" /p:ReferencePath="${{ github.workspace }}\libs"
                      if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

               - name: Copy ke Staging
                 shell: powershell
                 run: |
                      xcopy /E /Y /I "SKK\SKK\bin\Release\*" "D:\Citrix\Staging\SKKRNDAPPS\"

               - name: Selesai
                 shell: powershell
                 run: Write-Host "Deploy ke Staging berhasil"
